### ISSUE TITLE
Consensus color scheme

### ISSUE THREAD

**Issue by alephreish** [Janelia-Farm-Xfam/LogoServer#7]
The [consensus color scheme](http://skylign.org/help#colors_consensus) is said to correspond to that of clustalX. This is not correct: see clustalx's [default color scheme](https://salsa.debian.org/med-team/clustalx/blob/master/colprot.xml). I think the desired behavior is for skylign to stick to clustalx's color scheme or give it is an option, and/or provide a way to supply a custom color scheme.

**Comment by traviswheeler** [comment]
The color scheme is based on our understanding of clustalx's color scheme, as implemented in jalview: http://www.jalview.org/help/html/colourSchemes/clustal.html

There do appear to be subtle differences between the jalview definition and the specification you've linked to. I'm not sure where the divergence comes from, but it's what the skylign server is now set to. I'll agree that custom color schemes would be nice.
